### ISSUE TITLE
Relationship between ci-tools and project being built

### ISSUE THREAD

**Issue by barrc** [michaeltryby/ci-tools#8]
Hi @michaeltryby! I figured I would ask you this before I get in too deep since I am sure you know how all of these pieces fit together. I am trying to use ci-tools\windows\make.cmd to build SWMM 5.1.15. I'm not clear on whether the source code for SWMM needs to be inside of the ci-tools directory, or whether I need to put ci-tools inside of the SWMM directory, or whether they can be anywhere and I should just reference a path somewhere. Apologies if there's documentation I'm missing on this!

**Comment by michaeltryby** [comment]
Hey @barrc! Sorry about lack of documentation. I didn't think anyone was using this but me. 

Anyhow, you can clone ci-tools into the swmm project root directory.  Something like this ...

```
\> git clone https://github.com/USEPA/Stormwater-Management-Model.git
\> cd Stormwater-Management-Model
\> git clone https://github.com/michaeltryby/ci-tools.git
```

Then ci-tools folder is located in the swmm project root directory. With your working directory as swmm project root directory you can ...

```
\swmm> ci-tools\windows\make.cmd
\swmm> ci-tools\windows\before-nrtest.cmd
\swmm> ci-tools\windows\run-nrtests.cmd
```

**Comment by michaeltryby** [comment]
I use ci-tools to automate the GitHub Actions builds. So Actions configuration files are another place to see how they are used. 

https://github.com/USEPA/Stormwater-Management-Model/blob/develop/.github/workflows/build-and-test.yml

**Comment by michaeltryby** [comment]
Also, swmm-solver build artifacts are already built and located here ...

https://github.com/USEPA/Stormwater-Management-Model/releases/tag/v5.1.15

**Comment by barrc** [comment]
Thanks @michaeltryby! I should have looked at the releases tab...that should work great for my purposes. But also appreciate the context, I may need to build at some point.

For context I was looking at the ci-tools repo because it's mentioned in the build docs [here](https://github.com/USEPA/Stormwater-Management-Model/blob/develop/Build.md) but definitely got ahead of myself! Thanks again for the quick response, I'll close this.
